_wandb:
    value:
        cli_version: 0.29.0
        e:
            ckfhg7byljd12ipkiyb77vvijowbl2j1:
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "314571747328"
                        used: "83615711232"
                email: muppallakomaliitkgp2022@gmail.com
                executable: E:\Deep_RL\.venv\Scripts\python.exe
                git:
                    commit: bb9c83f8ce2f93e4646e97bd7e627a3b482bd601
                    remote: https://github.com/MUPPALLA2003/Deep_RL.git
                host: KOMAL
                memory:
                    total: "14870372352"
                os: Windows-10-10.0.26200-SP0
                program: -m training.dqn_train
                python: CPython 3.10.9
                root: E:\Deep_RL
                startedAt: "2026-08-31T16:52:15.746561Z"
                writerId: ckfhg7byljd12ipkiyb77vvijowbl2j1
        m: []
        python_version: 3.10.9
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 2
                - 13
                - 16
                - 61
            "4": 3.10.9
            "5": 0.29.0
            "8":
                - 3
            "12": 0.29.0
            "13": windows-amd64
environment:
    value:
        name: LunarLander-v3
        render_mode: rgb_array
logging:
    value:
        profiler_log_dir: logs/profiler
        run_name: dqn
        wandb_enabled: true
        wandb_mode: online
        wandb_project: lunarlander-dqn
profiler:
    value:
        active: 3
        export_mode: chrome
        repeat: 1
        wait: 1
        warmup: 1
train:
    value:
        batch_size: 64
        discount_factor: 0.99
        epsilon: 1
        epsilon_decay: 0.999
        game_tolerance: 10
        intermediate_dims: 128
        learning_rate: 0.001
        log_freq: 5
        max_memories: 100000
        min_epsilon: 0.05
        min_reward: 200
        num_actions: 4
        num_games: 500
        num_state_features: 8
        running_avg_steps: 25
        update_target_freq: 3
