environment:
  
  name : LunarLander-v3
  render_mode : rgb_array

train:
    
  num_games : 500
  update_target_freq : 3
  min_reward : 200
  game_tolerance : 10
  max_memories : 100000
  discount_factor : 0.99
  learning_rate : 0.001
  batch_size : 64
  num_state_features : 8
  num_actions : 4
  intermediate_dims : 128
  epsilon : 1.0
  epsilon_decay : 0.999
  min_epsilon : 0.05
  log_freq : 5 
  running_avg_steps : 25

logging:

  wandb_project : lunarlander-dqn
  run_name : d3qn
  wandb_mode : online
  wandb_enabled : true
  profiler_log_dir : logs/profiler

profiler:

  wait : 1
  warmup : 1
  active : 3
  repeat : 1
  export_mode : "chrome"  